### ISSUE TITLE
Factorial Trailing Zeroes - Leetcode problem

### ISSUE THREAD

**Issue by SairajGaonkar** [cartoonYu/LeetCodeSolution#4]
I appreciate your solution on the above problem.
Could you please help me understand your logic behind this solution?

**Comment by cartoonYu** [comment]
I'm afraid I have no idea about helping.Each problem has its own logic.
But I can give you some advice,first practice,exercise own logic.second keeping,I think it's end when the problem have been solved,keep optimize your solution.and last is refernce,there have comment area in lettcode,you can view others solution and form your own solution.

**Comment by cartoonYu** [comment]
> I appreciate your solution on the above problem.
> Could you please help me understand your logic behind this solution?

**Comment by cartoonYu** [comment]
> I appreciate your solution on the above problem.
> Could you please help me understand your logic behind this solution?

I'm afraid I have no idea about helping.Each problem has its own logic.
But I can give you some advice,first practice,exercise own logic.second keeping,I think it's end when the problem have been solved,keep optimize your solution.and last is refernce,there have comment area in lettcode,you can view others solution and form your own solution.

**Comment by cartoonYu** [comment]
Sorry,I have get the wrong point with your mean.could you please tell me the problem's ID?

**Comment by SairajGaonkar** [comment]
> Sorry,I have get the wrong point with your mean.could you please tell me the problem's ID?

Hi, 
The problem number is #172. Factorial Trailing Zeroes

**Comment by cartoonYu** [comment]
> > Sorry,I have get the wrong point with your mean.could you please tell me the problem's ID?
> 
> Hi,
> The problem number is #172. Factorial Trailing Zeroes

I think this solution is not about logic.it is about rule.you can find trailing zero only be the result with 2 multipart 5 by multiplication table.there haven't another method to get trailing zero.so we can statistics the number of 5.
Another think is enumeration.You can fingure out this rule by enumeration with some small text.

**Comment by SairajGaonkar** [comment]
> > > Sorry,I have get the wrong point with your mean.could you please tell me the problem's ID?
> > 
> > 
> > Hi,
> > The problem number is #172. Factorial Trailing Zeroes
> 
> I think this solution is not about logic.it is about rule.you can find trailing zero only be the result with 2 multipart 5 by multiplication table.there haven't another method to get trailing zero.so we can statistics the number of 5.
> Another think is enumeration.You can fingure out this rule by enumeration with some small text.

I agree, that was a good approach by you. Thank you.
